# Generated by Django 5.2.3 on 2025-07-08 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_attendance_break_duration_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='break_duration',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='break_end',
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_break_duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_work_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='break_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
